const BASE_PATH = "https://api.chatdaddy.tech/metrics".replace(/\/+$/, "");

/* tslint:disable */
/* eslint-disable */
/**
 * ChatDaddy Metrics Service
 * Query aggregate metrics
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
import type { RequestArgs } from '../base';
// @ts-ignore
import { COLLECTION_FORMATS, BaseAPI, RequiredError } from '../base';

/**
 * 
 * @export
 * @enum {string}
 */

export const AdminDashboardPeriod = {
    4Weeks: 'last-4-weeks',
    12Weeks: 'last-12-weeks',
    12Months: 'last-12-months'
} as const;

export type AdminDashboardPeriod = typeof AdminDashboardPeriod[keyof typeof AdminDashboardPeriod];


/**
 * 
 * @export
 * @interface AdminDashboardResponse
 */
export interface AdminDashboardResponse {
    /**
     * 
     * @type {Array<TeamData>}
     * @memberof AdminDashboardResponse
     */
    'items': Array<TeamData>;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardResponse
     */
    'nextCursor'?: string;
}
/**
 * 
 * @export
 * @interface AdminDashboardSort
 */
export interface AdminDashboardSort {
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardSort
     */
    'field': string;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardSort
     */
    'order': AdminDashboardSortOrderEnum;
}

export const AdminDashboardSortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type AdminDashboardSortOrderEnum = typeof AdminDashboardSortOrderEnum[keyof typeof AdminDashboardSortOrderEnum];

/**
 * 
 * @export
 * @enum {string}
 */

export const Aggregate = {
    Day: 'day',
    Week: 'week',
    Month: 'month'
} as const;

export type Aggregate = typeof Aggregate[keyof typeof Aggregate];


/**
 * @type AggregateTeamDataValue
 * @export
 */
export type AggregateTeamDataValue = ValueObject | { [key: string]: ValueObject; };

/**
 * Describe an array
 * @export
 * @interface ArrayPropertyDescriptor
 */
export interface ArrayPropertyDescriptor {
    /**
     * 
     * @type {string}
     * @memberof ArrayPropertyDescriptor
     */
    'type': ArrayPropertyDescriptorTypeEnum;
    /**
     * 
     * @type {DataPropertyDescriptor}
     * @memberof ArrayPropertyDescriptor
     */
    'items': DataPropertyDescriptor;
}

export const ArrayPropertyDescriptorTypeEnum = {
    Array: 'array'
} as const;

export type ArrayPropertyDescriptorTypeEnum = typeof ArrayPropertyDescriptorTypeEnum[keyof typeof ArrayPropertyDescriptorTypeEnum];

/**
 * 
 * @export
 * @interface ConditionalPropertyOption
 */
export interface ConditionalPropertyOption {
    /**
     * Stringified value of the option.
     * @type {string}
     * @memberof ConditionalPropertyOption
     */
    'valueStr': string;
    /**
     * 
     * @type {string}
     * @memberof ConditionalPropertyOption
     */
    'label': string;
}
/**
 * 
 * @export
 * @interface DashboardCreate
 */
export interface DashboardCreate {
    /**
     * 
     * @type {string}
     * @memberof DashboardCreate
     */
    'name': string;
    /**
     * 
     * @type {DashboardSchema}
     * @memberof DashboardCreate
     */
    'schema'?: DashboardSchema;
    /**
     * 
     * @type {DashboardMetadataPermissions}
     * @memberof DashboardCreate
     */
    'permissions'?: DashboardMetadataPermissions;
}
/**
 * 
 * @export
 * @interface DashboardData
 */
export interface DashboardData {
    /**
     * 
     * @type {string}
     * @memberof DashboardData
     */
    'id': string;
    /**
     * 
     * @type {Array<MetricsResult>}
     * @memberof DashboardData
     */
    'dataV2': Array<MetricsResult>;
}
/**
 * 
 * @export
 * @interface DashboardMetadata
 */
export interface DashboardMetadata {
    /**
     * 
     * @type {string}
     * @memberof DashboardMetadata
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardMetadata
     */
    'name': string;
    /**
     * Unique identifier for a user
     * @type {string}
     * @memberof DashboardMetadata
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardMetadata
     */
    'teamId': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof DashboardMetadata
     */
    'createdAt': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof DashboardMetadata
     */
    'updatedAt': string;
    /**
     * 
     * @type {DashboardSchema}
     * @memberof DashboardMetadata
     */
    'schema': DashboardSchema;
    /**
     * 
     * @type {DashboardMetadataPermissions}
     * @memberof DashboardMetadata
     */
    'permissions'?: DashboardMetadataPermissions;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const DashboardMetadataAccess = {
    Lvl1View: 'lvl1_view',
    Lvl2Edit: 'lvl2_edit'
} as const;

export type DashboardMetadataAccess = typeof DashboardMetadataAccess[keyof typeof DashboardMetadataAccess];


/**
 * 
 * @export
 * @interface DashboardMetadataPermissionItem
 */
export interface DashboardMetadataPermissionItem {
    /**
     * 
     * @type {string}
     * @memberof DashboardMetadataPermissionItem
     */
    'id': string;
    /**
     * 
     * @type {DashboardMetadataAccess}
     * @memberof DashboardMetadataPermissionItem
     */
    'access': DashboardMetadataAccess;
}


/**
 * 
 * @export
 * @interface DashboardMetadataPermissions
 */
export interface DashboardMetadataPermissions {
    /**
     * 
     * @type {NullableDashboardMetadataAccess}
     * @memberof DashboardMetadataPermissions
     */
    'allMembers'?: NullableDashboardMetadataAccess | null;
    /**
     * 
     * @type {Array<DashboardMetadataPermissionItem>}
     * @memberof DashboardMetadataPermissions
     */
    'users'?: Array<DashboardMetadataPermissionItem>;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const DashboardPeriod = {
    MonthToDate: 'month-to-date',
    QuarterToDate: 'quarter-to-date',
    YearToDate: 'year-to-date',
    Last4Weeks: 'last-4-weeks',
    Last12Weeks: 'last-12-weeks',
    Last12Months: 'last-12-months',
    Custom: 'custom'
} as const;

export type DashboardPeriod = typeof DashboardPeriod[keyof typeof DashboardPeriod];


/**
 * 
 * @export
 * @interface DashboardSchema
 */
export interface DashboardSchema {
    /**
     * 
     * @type {string}
     * @memberof DashboardSchema
     */
    'version': DashboardSchemaVersionEnum;
    /**
     * 
     * @type {Array<DashboardSchemaItemsInner>}
     * @memberof DashboardSchema
     */
    'items': Array<DashboardSchemaItemsInner>;
}

export const DashboardSchemaVersionEnum = {
    2: '2'
} as const;

export type DashboardSchemaVersionEnum = typeof DashboardSchemaVersionEnum[keyof typeof DashboardSchemaVersionEnum];

/**
 * 
 * @export
 * @interface DashboardSchemaItem
 */
export interface DashboardSchemaItem {
    /**
     * 
     * @type {string}
     * @memberof DashboardSchemaItem
     */
    'id': string;
    /**
     * 
     * @type {DashboardVisualizationType}
     * @memberof DashboardSchemaItem
     */
    'visualizationType': DashboardVisualizationType;
    /**
     * 
     * @type {string}
     * @memberof DashboardSchemaItem
     */
    'metricId': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardSchemaItem
     */
    'name': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DashboardSchemaItem
     */
    'filter'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof DashboardSchemaItem
     */
    'breakdown'?: string;
    /**
     * Hide the default value in the breakdown.
     * @type {boolean}
     * @memberof DashboardSchemaItem
     */
    'hideDefaultInBreakdown'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DashboardSchemaItem
     */
    'includePreviousPeriod'?: boolean;
}


/**
 * @type DashboardSchemaItemsInner
 * @export
 */
export type DashboardSchemaItemsInner = DashboardSchemaItem | TextSchemaItem;

/**
 * 
 * @export
 * @interface DashboardUpdate
 */
export interface DashboardUpdate {
    /**
     * 
     * @type {string}
     * @memberof DashboardUpdate
     */
    'name'?: string;
    /**
     * 
     * @type {DashboardSchema}
     * @memberof DashboardUpdate
     */
    'schema'?: DashboardSchema;
    /**
     * 
     * @type {DashboardMetadataPermissions}
     * @memberof DashboardUpdate
     */
    'permissions'?: DashboardMetadataPermissions;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const DashboardVisualizationType = {
    Histogram: 'histogram',
    PieChart: 'pie-chart',
    Table: 'table',
    Snapshot: 'snapshot',
    SimpleSnapshot: 'simple-snapshot'
} as const;

export type DashboardVisualizationType = typeof DashboardVisualizationType[keyof typeof DashboardVisualizationType];


/**
 * 
 * @export
 * @interface DashboardWithData
 */
export interface DashboardWithData {
    /**
     * 
     * @type {string}
     * @memberof DashboardWithData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardWithData
     */
    'name': string;
    /**
     * Unique identifier for a user
     * @type {string}
     * @memberof DashboardWithData
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof DashboardWithData
     */
    'teamId': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof DashboardWithData
     */
    'createdAt': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof DashboardWithData
     */
    'updatedAt': string;
    /**
     * 
     * @type {DashboardSchema}
     * @memberof DashboardWithData
     */
    'schema': DashboardSchema;
    /**
     * 
     * @type {DashboardMetadataPermissions}
     * @memberof DashboardWithData
     */
    'permissions'?: DashboardMetadataPermissions;
    /**
     * 
     * @type {Array<MetricsResult>}
     * @memberof DashboardWithData
     */
    'dataV2': Array<MetricsResult>;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const DataAggregateType = {
    Avg: 'avg',
    Sum: 'sum'
} as const;

export type DataAggregateType = typeof DataAggregateType[keyof typeof DataAggregateType];


/**
 * Description of a property
 * @export
 * @interface DataProperty
 */
export type DataProperty = DataPropertyDescriptor & PropertyMetadata
/**
 * @type DataPropertyDescriptor
 * @export
 */
export type DataPropertyDescriptor = SimplePropertyDescriptor | ArrayPropertyDescriptor | MapPropertyDescriptor | OAuthPropertyDescriptor;

/**
 * 
 * @export
 * @interface DateRange
 */
export interface DateRange {
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof DateRange
     */
    'start': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof DateRange
     */
    'end': string;
}
/**
 * 
 * @export
 * @interface DisplayIcon
 */
export interface DisplayIcon {
    /**
     * Material symbol name
     * @type {string}
     * @memberof DisplayIcon
     */
    'name': string;
    /**
     * Color name, hex code or theme color
     * @type {string}
     * @memberof DisplayIcon
     */
    'color'?: string;
}
/**
 * 
 * @export
 * @interface GetDashboardBySchemaRequest
 */
export interface GetDashboardBySchemaRequest {
    /**
     * 
     * @type {DashboardSchema}
     * @memberof GetDashboardBySchemaRequest
     */
    'schema': DashboardSchema;
}
/**
 * 
 * @export
 * @interface GetDashboardMetadatas200Response
 */
export interface GetDashboardMetadatas200Response {
    /**
     * 
     * @type {Array<DashboardMetadata>}
     * @memberof GetDashboardMetadatas200Response
     */
    'items': Array<DashboardMetadata>;
}
/**
 * 
 * @export
 * @interface GetInitData200Response
 */
export interface GetInitData200Response {
    /**
     * 
     * @type {DashboardSchema}
     * @memberof GetInitData200Response
     */
    'adminDashboardSchema'?: DashboardSchema;
    /**
     * 
     * @type {Array<DashboardMetadata>}
     * @memberof GetInitData200Response
     */
    'dashboards': Array<DashboardMetadata>;
    /**
     * 
     * @type {Array<MetricConfig>}
     * @memberof GetInitData200Response
     */
    'configs': Array<MetricConfig>;
    /**
     * 
     * @type {DashboardData}
     * @memberof GetInitData200Response
     */
    'data': DashboardData;
    /**
     * 
     * @type {GetInitData200ResponseDefaultDashboard}
     * @memberof GetInitData200Response
     */
    'defaultDashboard'?: GetInitData200ResponseDefaultDashboard;
}
/**
 * Present if the data being fetched is for the default dashboard. 
 * @export
 * @interface GetInitData200ResponseDefaultDashboard
 */
export interface GetInitData200ResponseDefaultDashboard {
    /**
     * 
     * @type {string}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'name': string;
    /**
     * Unique identifier for a user
     * @type {string}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'teamId': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'createdAt': string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'updatedAt': string;
    /**
     * 
     * @type {DashboardSchema}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'schema': DashboardSchema;
    /**
     * 
     * @type {DashboardMetadataPermissions}
     * @memberof GetInitData200ResponseDefaultDashboard
     */
    'permissions'?: DashboardMetadataPermissions;
}
/**
 * Describe a map
 * @export
 * @interface MapPropertyDescriptor
 */
export interface MapPropertyDescriptor {
    /**
     * 
     * @type {string}
     * @memberof MapPropertyDescriptor
     */
    'type': MapPropertyDescriptorTypeEnum;
    /**
     * 
     * @type {Array<DataProperty>}
     * @memberof MapPropertyDescriptor
     */
    'properties': Array<DataProperty>;
    /**
     * 
     * @type {DataPropertyDescriptor}
     * @memberof MapPropertyDescriptor
     */
    'additionalProperties'?: DataPropertyDescriptor;
}

export const MapPropertyDescriptorTypeEnum = {
    Map: 'map'
} as const;

export type MapPropertyDescriptorTypeEnum = typeof MapPropertyDescriptorTypeEnum[keyof typeof MapPropertyDescriptorTypeEnum];

/**
 * 
 * @export
 * @interface Metric
 */
export interface Metric {
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof Metric
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    'value': number;
    /**
     * Number of data points in this metric. Only present for when the value is not a count 
     * @type {number}
     * @memberof Metric
     */
    'count'?: number;
}
/**
 * 
 * @export
 * @interface MetricAllOf
 */
export interface MetricAllOf {
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof MetricAllOf
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface MetricConfig
 */
export interface MetricConfig {
    /**
     * 
     * @type {string}
     * @memberof MetricConfig
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MetricConfig
     */
    'defaultName': string;
    /**
     * 
     * @type {string}
     * @memberof MetricConfig
     */
    'valueFormat'?: MetricConfigValueFormatEnum;
    /**
     * 
     * @type {DataAggregateType}
     * @memberof MetricConfig
     */
    'aggregationType'?: DataAggregateType;
    /**
     * Whether an increase in the metric is good or bad.
     * @type {boolean}
     * @memberof MetricConfig
     */
    'isIncreaseGood'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MetricConfig
     */
    'description'?: string;
    /**
     * 
     * @type {Array<MetricConfigProperty>}
     * @memberof MetricConfig
     */
    'properties': Array<MetricConfigProperty>;
    /**
     * 
     * @type {Array<DashboardVisualizationType>}
     * @memberof MetricConfig
     */
    'disallowedVisualisations'?: Array<DashboardVisualizationType>;
}

export const MetricConfigValueFormatEnum = {
    Count: 'count',
    DurationSeconds: 'durationSeconds',
    Percentage: 'percentage'
} as const;

export type MetricConfigValueFormatEnum = typeof MetricConfigValueFormatEnum[keyof typeof MetricConfigValueFormatEnum];

/**
 * 
 * @export
 * @interface MetricConfigProperty
 */
export type MetricConfigProperty = DataProperty & {
    /**
     * Title to show when the value is none. Use \"{{appName}}\" to refer to the app name. 
     * @type {string}
     * @memberof MetricConfigProperty
     */
    'noneValueTitle'?: string;
}


/**
 * 
 * @export
 * @interface MetricConfigPropertyAllOf
 */
export interface MetricConfigPropertyAllOf {
    /**
     * Title to show when the value is none. Use \"{{appName}}\" to refer to the app name. 
     * @type {string}
     * @memberof MetricConfigPropertyAllOf
     */
    'noneValueTitle'?: string;
}
/**
 * @type MetricsResult
 * @export
 */
export type MetricsResult = MetricsResultHistogram | MetricsResultTotal;

/**
 * 
 * @export
 * @interface MetricsResultHistogram
 */
export interface MetricsResultHistogram {
    /**
     * 
     * @type {string}
     * @memberof MetricsResultHistogram
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MetricsResultHistogram
     */
    'visualizationType': MetricsResultHistogramVisualizationTypeEnum;
    /**
     * 
     * @type {{ [key: string]: Array<Metric>; }}
     * @memberof MetricsResultHistogram
     */
    'lines': { [key: string]: Array<Metric>; };
    /**
     * 
     * @type {{ [key: string]: Array<Metric>; }}
     * @memberof MetricsResultHistogram
     */
    'previousPeriodLines'?: { [key: string]: Array<Metric>; };
}

export const MetricsResultHistogramVisualizationTypeEnum = {
    Histogram: 'histogram'
} as const;

export type MetricsResultHistogramVisualizationTypeEnum = typeof MetricsResultHistogramVisualizationTypeEnum[keyof typeof MetricsResultHistogramVisualizationTypeEnum];

/**
 * 
 * @export
 * @interface MetricsResultTotal
 */
export interface MetricsResultTotal {
    /**
     * 
     * @type {string}
     * @memberof MetricsResultTotal
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MetricsResultTotal
     */
    'visualizationType': MetricsResultTotalVisualizationTypeEnum;
    /**
     * 
     * @type {{ [key: string]: ValueObject; }}
     * @memberof MetricsResultTotal
     */
    'values': { [key: string]: ValueObject; };
    /**
     * 
     * @type {{ [key: string]: ValueObject; }}
     * @memberof MetricsResultTotal
     */
    'previousPeriodValues'?: { [key: string]: ValueObject; };
}

export const MetricsResultTotalVisualizationTypeEnum = {
    Total: 'total'
} as const;

export type MetricsResultTotalVisualizationTypeEnum = typeof MetricsResultTotalVisualizationTypeEnum[keyof typeof MetricsResultTotalVisualizationTypeEnum];

/**
 * 
 * @export
 * @enum {string}
 */

export const NullableDashboardMetadataAccess = {
    Lvl1View: 'lvl1_view',
    Lvl2Edit: 'lvl2_edit',
    Null: null as null
} as const;

export type NullableDashboardMetadataAccess = typeof NullableDashboardMetadataAccess[keyof typeof NullableDashboardMetadataAccess];


/**
 * describe OAuth input for access tokens
 * @export
 * @interface OAuthPropertyDescriptor
 */
export interface OAuthPropertyDescriptor {
    /**
     * 
     * @type {string}
     * @memberof OAuthPropertyDescriptor
     */
    'type': OAuthPropertyDescriptorTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OAuthPropertyDescriptor
     */
    'url'?: string;
}

export const OAuthPropertyDescriptorTypeEnum = {
    Oauth: 'oauth'
} as const;

export type OAuthPropertyDescriptorTypeEnum = typeof OAuthPropertyDescriptorTypeEnum[keyof typeof OAuthPropertyDescriptorTypeEnum];

/**
 * 
 * @export
 * @interface PropertyMetadata
 */
export interface PropertyMetadata {
    /**
     * 
     * @type {string}
     * @memberof PropertyMetadata
     */
    'propertyPath': string;
    /**
     * 
     * @type {string}
     * @memberof PropertyMetadata
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PropertyMetadata
     */
    'description'?: string;
    /**
     * 
     * @type {DisplayIcon}
     * @memberof PropertyMetadata
     */
    'icon'?: DisplayIcon;
    /**
     * Is the property always expected to be present.
     * @type {boolean}
     * @memberof PropertyMetadata
     */
    'required'?: boolean;
}
/**
 * Simple string/number/boolean type
 * @export
 * @interface SimplePropertyDescriptor
 */
export interface SimplePropertyDescriptor {
    /**
     * 
     * @type {SimplePropertyType}
     * @memberof SimplePropertyDescriptor
     */
    'type': SimplePropertyType;
    /**
     * 
     * @type {Array<ConditionalPropertyOption>}
     * @memberof SimplePropertyDescriptor
     */
    'options'?: Array<ConditionalPropertyOption>;
    /**
     * Format of the property.  Only valid for string type. For example, \'date-time\' for timestamp properties
     * @type {string}
     * @memberof SimplePropertyDescriptor
     */
    'format'?: string;
    /**
     * Minimum number of stages required in the board for the condition to be valid. Only valid for \"board\" type
     * @type {number}
     * @memberof SimplePropertyDescriptor
     */
    'minimumStages'?: number;
}


/**
 * Type of property. - string, number, boolean: Simple property type - timestamp: timestamp string in ISO format - timezone: timezone in offset format - time: time in 24 hour format - channel, tag, team_member, chat, board_stage, board, ticket:     Reference to another object by ID - custom_field: Object of type { name: string, value: string } - duration: integer representing seconds - credit_consumption_type: all credit consumption types 
 * @export
 * @enum {string}
 */

export const SimplePropertyType = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Channel: 'channel',
    Tag: 'tag',
    CustomField: 'custom_field',
    Timestamp: 'timestamp',
    CountryCode: 'country_code',
    TeamMember: 'team_member',
    Chat: 'chat',
    BoardStage: 'board_stage',
    Duration: 'duration',
    Ticket: 'ticket',
    Board: 'board',
    Oauth: 'oauth',
    Timezone: 'timezone',
    Time: 'time',
    CreditConsumptionType: 'credit_consumption_type'
} as const;

export type SimplePropertyType = typeof SimplePropertyType[keyof typeof SimplePropertyType];


/**
 * 
 * @export
 * @interface TeamData
 */
export interface TeamData {
    /**
     * 
     * @type {string}
     * @memberof TeamData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamData
     */
    'customerId': string;
    /**
     * 
     * @type {string}
     * @memberof TeamData
     */
    'name'?: string;
    /**
     * An ISO formatted timestamp
     * @type {string}
     * @memberof TeamData
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof TeamData
     */
    'industry': string;
    /**
     * 
     * @type {string}
     * @memberof TeamData
     */
    'region': string;
    /**
     * 
     * @type {TeamDataData}
     * @memberof TeamData
     */
    'data': TeamDataData;
}
/**
 * 
 * @export
 * @interface TeamDataData
 */
export interface TeamDataData {
    /**
     * 
     * @type {{ [key: string]: AggregateTeamDataValue; }}
     * @memberof TeamDataData
     */
    'static'?: { [key: string]: AggregateTeamDataValue; };
    /**
     * 
     * @type {{ [key: string]: AggregateTeamDataValue; }}
     * @memberof TeamDataData
     */
    'last4Weeks'?: { [key: string]: AggregateTeamDataValue; };
    /**
     * 
     * @type {{ [key: string]: AggregateTeamDataValue; }}
     * @memberof TeamDataData
     */
    'last12Weeks'?: { [key: string]: AggregateTeamDataValue; };
    /**
     * 
     * @type {{ [key: string]: AggregateTeamDataValue; }}
     * @memberof TeamDataData
     */
    'last12Months'?: { [key: string]: AggregateTeamDataValue; };
}
/**
 * 
 * @export
 * @interface TextSchemaItem
 */
export interface TextSchemaItem {
    /**
     * 
     * @type {string}
     * @memberof TextSchemaItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TextSchemaItem
     */
    'title': string;
}
/**
 * 
 * @export
 * @interface ValueObject
 */
export interface ValueObject {
    /**
     * 
     * @type {number}
     * @memberof ValueObject
     */
    'value': number;
    /**
     * Number of data points in this metric. Only present for when the value is not a count 
     * @type {number}
     * @memberof ValueObject
     */
    'count'?: number;
}

/**
 * DashboardApi - axios parameter creator
 * @export
 */
export const DashboardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new dashboard metadata
         * @param {'1' | '2'} [version] Which version of the schema to use.
         * @param {DashboardCreate} [dashboardCreate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDashboardMetadata: async (version?: '1' | '2', dashboardCreate?: DashboardCreate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard/metadatas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["DASHBOARD_CREATE"], configuration)

            if (version !== undefined) {
                localVarQueryParameter['version'] = version;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dashboardCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a dashboard metadata
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDashboardMetadata: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteDashboardMetadata', 'id', id)
            const localVarPath = `/dashboard/metadatas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["DASHBOARD_DELETE"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get admin dashboards
         * @param {AdminDashboardPeriod} period 
         * @param {Array<string>} [teamIds] Fetch specific teams by ID
         * @param {string} [customerId] 
         * @param {number} [count] Numboer of items to fetch.
         * @param {string} [cursor] Cursor to fetch the next page of dashboards.
         * @param {string} [industry] 
         * @param {string} [region] 
         * @param {AdminDashboardSort} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminDashboards: async (period: AdminDashboardPeriod, teamIds?: Array<string>, customerId?: string, count?: number, cursor?: string, industry?: string, region?: string, sort?: AdminDashboardSort, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'period' is not null or undefined
            assertParamExists('getAdminDashboards', 'period', period)
            const localVarPath = `/dashboard/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["ADMIN_PANEL_ACCESS"], configuration)

            if (teamIds) {
                localVarQueryParameter['teamIds'] = teamIds;
            }

            if (customerId !== undefined) {
                localVarQueryParameter['customerId'] = customerId;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (industry !== undefined) {
                localVarQueryParameter['industry'] = industry;
            }

            if (region !== undefined) {
                localVarQueryParameter['region'] = region;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get dashboard data
         * @param {DashboardPeriod} period 
         * @param {Aggregate} aggregate Timeframe to aggregate the data in.
         * @param {string} [id] Dashboard ID to fetch data for. If not provided, the default dashboard will be returned.
         * @param {DateRange} [customDateRange] Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
         * @param {string} [timezoneOffset] Timezone offset to query the data in.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboard: async (period: DashboardPeriod, aggregate: Aggregate, id?: string, customDateRange?: DateRange, timezoneOffset?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'period' is not null or undefined
            assertParamExists('getDashboard', 'period', period)
            // verify required parameter 'aggregate' is not null or undefined
            assertParamExists('getDashboard', 'aggregate', aggregate)
            const localVarPath = `/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["METRICS_GET"], configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (customDateRange !== undefined) {
                localVarQueryParameter['customDateRange'] = customDateRange;
            }

            if (timezoneOffset !== undefined) {
                localVarQueryParameter['timezoneOffset'] = timezoneOffset;
            }

            if (aggregate !== undefined) {
                localVarQueryParameter['aggregate'] = aggregate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get dashboard data by schema
         * @param {DashboardPeriod} period 
         * @param {Aggregate} aggregate Timeframe to aggregate the data in.
         * @param {DateRange} [customDateRange] Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
         * @param {string} [timezoneOffset] Timezone offset to query the data in.
         * @param {GetDashboardBySchemaRequest} [getDashboardBySchemaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardBySchema: async (period: DashboardPeriod, aggregate: Aggregate, customDateRange?: DateRange, timezoneOffset?: string, getDashboardBySchemaRequest?: GetDashboardBySchemaRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'period' is not null or undefined
            assertParamExists('getDashboardBySchema', 'period', period)
            // verify required parameter 'aggregate' is not null or undefined
            assertParamExists('getDashboardBySchema', 'aggregate', aggregate)
            const localVarPath = `/dashboard/get-by-schema`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["METRICS_GET"], configuration)

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (customDateRange !== undefined) {
                localVarQueryParameter['customDateRange'] = customDateRange;
            }

            if (timezoneOffset !== undefined) {
                localVarQueryParameter['timezoneOffset'] = timezoneOffset;
            }

            if (aggregate !== undefined) {
                localVarQueryParameter['aggregate'] = aggregate;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getDashboardBySchemaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get dashboard metadatas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardMetadatas: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard/metadatas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["METRICS_GET"], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get initial data
         * @param {DashboardPeriod} period 
         * @param {Aggregate} aggregate Timeframe to aggregate the data in.
         * @param {string} [id] Dashboard ID to fetch data for. If not provided, the default dashboard will be returned.
         * @param {DateRange} [customDateRange] Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
         * @param {string} [timezoneOffset] Timezone offset to query the data in.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInitData: async (period: DashboardPeriod, aggregate: Aggregate, id?: string, customDateRange?: DateRange, timezoneOffset?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'period' is not null or undefined
            assertParamExists('getInitData', 'period', period)
            // verify required parameter 'aggregate' is not null or undefined
            assertParamExists('getInitData', 'aggregate', aggregate)
            const localVarPath = `/initData`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["METRICS_GET"], configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (customDateRange !== undefined) {
                localVarQueryParameter['customDateRange'] = customDateRange;
            }

            if (timezoneOffset !== undefined) {
                localVarQueryParameter['timezoneOffset'] = timezoneOffset;
            }

            if (aggregate !== undefined) {
                localVarQueryParameter['aggregate'] = aggregate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a dashboard metadata
         * @param {string} id 
         * @param {DashboardUpdate} [dashboardUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDashboardMetadata: async (id: string, dashboardUpdate?: DashboardUpdate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateDashboardMetadata', 'id', id)
            const localVarPath = `/dashboard/metadatas/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication chatdaddy required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "chatdaddy", ["METRICS_GET"], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dashboardUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardApi - functional programming interface
 * @export
 */
export const DashboardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DashboardApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new dashboard metadata
         * @param {'1' | '2'} [version] Which version of the schema to use.
         * @param {DashboardCreate} [dashboardCreate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDashboardMetadata(version?: '1' | '2', dashboardCreate?: DashboardCreate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardMetadata>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDashboardMetadata(version, dashboardCreate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete a dashboard metadata
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDashboardMetadata(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDashboardMetadata(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get admin dashboards
         * @param {AdminDashboardPeriod} period 
         * @param {Array<string>} [teamIds] Fetch specific teams by ID
         * @param {string} [customerId] 
         * @param {number} [count] Numboer of items to fetch.
         * @param {string} [cursor] Cursor to fetch the next page of dashboards.
         * @param {string} [industry] 
         * @param {string} [region] 
         * @param {AdminDashboardSort} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdminDashboards(period: AdminDashboardPeriod, teamIds?: Array<string>, customerId?: string, count?: number, cursor?: string, industry?: string, region?: string, sort?: AdminDashboardSort, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminDashboardResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdminDashboards(period, teamIds, customerId, count, cursor, industry, region, sort, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get dashboard data
         * @param {DashboardPeriod} period 
         * @param {Aggregate} aggregate Timeframe to aggregate the data in.
         * @param {string} [id] Dashboard ID to fetch data for. If not provided, the default dashboard will be returned.
         * @param {DateRange} [customDateRange] Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
         * @param {string} [timezoneOffset] Timezone offset to query the data in.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboard(period: DashboardPeriod, aggregate: Aggregate, id?: string, customDateRange?: DateRange, timezoneOffset?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardWithData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboard(period, aggregate, id, customDateRange, timezoneOffset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get dashboard data by schema
         * @param {DashboardPeriod} period 
         * @param {Aggregate} aggregate Timeframe to aggregate the data in.
         * @param {DateRange} [customDateRange] Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
         * @param {string} [timezoneOffset] Timezone offset to query the data in.
         * @param {GetDashboardBySchemaRequest} [getDashboardBySchemaRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboardBySchema(period: DashboardPeriod, aggregate: Aggregate, customDateRange?: DateRange, timezoneOffset?: string, getDashboardBySchemaRequest?: GetDashboardBySchemaRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboardBySchema(period, aggregate, customDateRange, timezoneOffset, getDashboardBySchemaRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get dashboard metadatas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboardMetadatas(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetDashboardMetadatas200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboardMetadatas(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get initial data
         * @param {DashboardPeriod} period 
         * @param {Aggregate} aggregate Timeframe to aggregate the data in.
         * @param {string} [id] Dashboard ID to fetch data for. If not provided, the default dashboard will be returned.
         * @param {DateRange} [customDateRange] Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
         * @param {string} [timezoneOffset] Timezone offset to query the data in.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInitData(period: DashboardPeriod, aggregate: Aggregate, id?: string, customDateRange?: DateRange, timezoneOffset?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetInitData200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInitData(period, aggregate, id, customDateRange, timezoneOffset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update a dashboard metadata
         * @param {string} id 
         * @param {DashboardUpdate} [dashboardUpdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDashboardMetadata(id: string, dashboardUpdate?: DashboardUpdate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDashboardMetadata(id, dashboardUpdate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DashboardApi - factory interface
 * @export
 */
export const DashboardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DashboardApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new dashboard metadata
         * @param {DashboardApiCreateDashboardMetadataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDashboardMetadata(requestParameters: DashboardApiCreateDashboardMetadataRequest = {}, options?: AxiosRequestConfig): AxiosPromise<DashboardMetadata> {
            return localVarFp.createDashboardMetadata(requestParameters.version, requestParameters.dashboardCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a dashboard metadata
         * @param {DashboardApiDeleteDashboardMetadataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDashboardMetadata(requestParameters: DashboardApiDeleteDashboardMetadataRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteDashboardMetadata(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get admin dashboards
         * @param {DashboardApiGetAdminDashboardsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdminDashboards(requestParameters: DashboardApiGetAdminDashboardsRequest, options?: AxiosRequestConfig): AxiosPromise<AdminDashboardResponse> {
            return localVarFp.getAdminDashboards(requestParameters.period, requestParameters.teamIds, requestParameters.customerId, requestParameters.count, requestParameters.cursor, requestParameters.industry, requestParameters.region, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get dashboard data
         * @param {DashboardApiGetDashboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboard(requestParameters: DashboardApiGetDashboardRequest, options?: AxiosRequestConfig): AxiosPromise<DashboardWithData> {
            return localVarFp.getDashboard(requestParameters.period, requestParameters.aggregate, requestParameters.id, requestParameters.customDateRange, requestParameters.timezoneOffset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get dashboard data by schema
         * @param {DashboardApiGetDashboardBySchemaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardBySchema(requestParameters: DashboardApiGetDashboardBySchemaRequest, options?: AxiosRequestConfig): AxiosPromise<DashboardData> {
            return localVarFp.getDashboardBySchema(requestParameters.period, requestParameters.aggregate, requestParameters.customDateRange, requestParameters.timezoneOffset, requestParameters.getDashboardBySchemaRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get dashboard metadatas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardMetadatas(options?: AxiosRequestConfig): AxiosPromise<GetDashboardMetadatas200Response> {
            return localVarFp.getDashboardMetadatas(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get initial data
         * @param {DashboardApiGetInitDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInitData(requestParameters: DashboardApiGetInitDataRequest, options?: AxiosRequestConfig): AxiosPromise<GetInitData200Response> {
            return localVarFp.getInitData(requestParameters.period, requestParameters.aggregate, requestParameters.id, requestParameters.customDateRange, requestParameters.timezoneOffset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a dashboard metadata
         * @param {DashboardApiUpdateDashboardMetadataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDashboardMetadata(requestParameters: DashboardApiUpdateDashboardMetadataRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateDashboardMetadata(requestParameters.id, requestParameters.dashboardUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createDashboardMetadata operation in DashboardApi.
 * @export
 * @interface DashboardApiCreateDashboardMetadataRequest
 */
export interface DashboardApiCreateDashboardMetadataRequest {
    /**
     * Which version of the schema to use.
     * @type {'1' | '2'}
     * @memberof DashboardApiCreateDashboardMetadata
     */
    readonly version?: '1' | '2'

    /**
     * 
     * @type {DashboardCreate}
     * @memberof DashboardApiCreateDashboardMetadata
     */
    readonly dashboardCreate?: DashboardCreate
}

/**
 * Request parameters for deleteDashboardMetadata operation in DashboardApi.
 * @export
 * @interface DashboardApiDeleteDashboardMetadataRequest
 */
export interface DashboardApiDeleteDashboardMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof DashboardApiDeleteDashboardMetadata
     */
    readonly id: string
}

/**
 * Request parameters for getAdminDashboards operation in DashboardApi.
 * @export
 * @interface DashboardApiGetAdminDashboardsRequest
 */
export interface DashboardApiGetAdminDashboardsRequest {
    /**
     * 
     * @type {AdminDashboardPeriod}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly period: AdminDashboardPeriod

    /**
     * Fetch specific teams by ID
     * @type {Array<string>}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly teamIds?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly customerId?: string

    /**
     * Numboer of items to fetch.
     * @type {number}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly count?: number

    /**
     * Cursor to fetch the next page of dashboards.
     * @type {string}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly cursor?: string

    /**
     * 
     * @type {string}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly industry?: string

    /**
     * 
     * @type {string}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly region?: string

    /**
     * 
     * @type {AdminDashboardSort}
     * @memberof DashboardApiGetAdminDashboards
     */
    readonly sort?: AdminDashboardSort
}

/**
 * Request parameters for getDashboard operation in DashboardApi.
 * @export
 * @interface DashboardApiGetDashboardRequest
 */
export interface DashboardApiGetDashboardRequest {
    /**
     * 
     * @type {DashboardPeriod}
     * @memberof DashboardApiGetDashboard
     */
    readonly period: DashboardPeriod

    /**
     * Timeframe to aggregate the data in.
     * @type {Aggregate}
     * @memberof DashboardApiGetDashboard
     */
    readonly aggregate: Aggregate

    /**
     * Dashboard ID to fetch data for. If not provided, the default dashboard will be returned.
     * @type {string}
     * @memberof DashboardApiGetDashboard
     */
    readonly id?: string

    /**
     * Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
     * @type {DateRange}
     * @memberof DashboardApiGetDashboard
     */
    readonly customDateRange?: DateRange

    /**
     * Timezone offset to query the data in.
     * @type {string}
     * @memberof DashboardApiGetDashboard
     */
    readonly timezoneOffset?: string
}

/**
 * Request parameters for getDashboardBySchema operation in DashboardApi.
 * @export
 * @interface DashboardApiGetDashboardBySchemaRequest
 */
export interface DashboardApiGetDashboardBySchemaRequest {
    /**
     * 
     * @type {DashboardPeriod}
     * @memberof DashboardApiGetDashboardBySchema
     */
    readonly period: DashboardPeriod

    /**
     * Timeframe to aggregate the data in.
     * @type {Aggregate}
     * @memberof DashboardApiGetDashboardBySchema
     */
    readonly aggregate: Aggregate

    /**
     * Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
     * @type {DateRange}
     * @memberof DashboardApiGetDashboardBySchema
     */
    readonly customDateRange?: DateRange

    /**
     * Timezone offset to query the data in.
     * @type {string}
     * @memberof DashboardApiGetDashboardBySchema
     */
    readonly timezoneOffset?: string

    /**
     * 
     * @type {GetDashboardBySchemaRequest}
     * @memberof DashboardApiGetDashboardBySchema
     */
    readonly getDashboardBySchemaRequest?: GetDashboardBySchemaRequest
}

/**
 * Request parameters for getInitData operation in DashboardApi.
 * @export
 * @interface DashboardApiGetInitDataRequest
 */
export interface DashboardApiGetInitDataRequest {
    /**
     * 
     * @type {DashboardPeriod}
     * @memberof DashboardApiGetInitData
     */
    readonly period: DashboardPeriod

    /**
     * Timeframe to aggregate the data in.
     * @type {Aggregate}
     * @memberof DashboardApiGetInitData
     */
    readonly aggregate: Aggregate

    /**
     * Dashboard ID to fetch data for. If not provided, the default dashboard will be returned.
     * @type {string}
     * @memberof DashboardApiGetInitData
     */
    readonly id?: string

    /**
     * Custom date range to query the data in. Only required if period is set to \&quot;custom\&quot;
     * @type {DateRange}
     * @memberof DashboardApiGetInitData
     */
    readonly customDateRange?: DateRange

    /**
     * Timezone offset to query the data in.
     * @type {string}
     * @memberof DashboardApiGetInitData
     */
    readonly timezoneOffset?: string
}

/**
 * Request parameters for updateDashboardMetadata operation in DashboardApi.
 * @export
 * @interface DashboardApiUpdateDashboardMetadataRequest
 */
export interface DashboardApiUpdateDashboardMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof DashboardApiUpdateDashboardMetadata
     */
    readonly id: string

    /**
     * 
     * @type {DashboardUpdate}
     * @memberof DashboardApiUpdateDashboardMetadata
     */
    readonly dashboardUpdate?: DashboardUpdate
}

/**
 * DashboardApi - object-oriented interface
 * @export
 * @class DashboardApi
 * @extends {BaseAPI}
 */
export class DashboardApi extends BaseAPI {
    /**
     * 
     * @summary Create a new dashboard metadata
     * @param {DashboardApiCreateDashboardMetadataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public createDashboardMetadata(requestParameters: DashboardApiCreateDashboardMetadataRequest = {}, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).createDashboardMetadata(requestParameters.version, requestParameters.dashboardCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a dashboard metadata
     * @param {DashboardApiDeleteDashboardMetadataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public deleteDashboardMetadata(requestParameters: DashboardApiDeleteDashboardMetadataRequest, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).deleteDashboardMetadata(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get admin dashboards
     * @param {DashboardApiGetAdminDashboardsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getAdminDashboards(requestParameters: DashboardApiGetAdminDashboardsRequest, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getAdminDashboards(requestParameters.period, requestParameters.teamIds, requestParameters.customerId, requestParameters.count, requestParameters.cursor, requestParameters.industry, requestParameters.region, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get dashboard data
     * @param {DashboardApiGetDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getDashboard(requestParameters: DashboardApiGetDashboardRequest, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getDashboard(requestParameters.period, requestParameters.aggregate, requestParameters.id, requestParameters.customDateRange, requestParameters.timezoneOffset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get dashboard data by schema
     * @param {DashboardApiGetDashboardBySchemaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getDashboardBySchema(requestParameters: DashboardApiGetDashboardBySchemaRequest, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getDashboardBySchema(requestParameters.period, requestParameters.aggregate, requestParameters.customDateRange, requestParameters.timezoneOffset, requestParameters.getDashboardBySchemaRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get dashboard metadatas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getDashboardMetadatas(options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getDashboardMetadatas(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get initial data
     * @param {DashboardApiGetInitDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getInitData(requestParameters: DashboardApiGetInitDataRequest, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getInitData(requestParameters.period, requestParameters.aggregate, requestParameters.id, requestParameters.customDateRange, requestParameters.timezoneOffset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a dashboard metadata
     * @param {DashboardApiUpdateDashboardMetadataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public updateDashboardMetadata(requestParameters: DashboardApiUpdateDashboardMetadataRequest, options?: AxiosRequestConfig) {
        return DashboardApiFp(this.configuration).updateDashboardMetadata(requestParameters.id, requestParameters.dashboardUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}


